services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    env_file:
      - .env
    depends_on:
      - voicevox_engine
      - db
    command: /bin/sh -c "npx prisma migrate deploy && npm start"

  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox_engine
    ports:
      - "50021:50021"

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'db_name'
    ports:
      - "5432:5432"